import { ProcessedRequest } from '../../types/domain';

export const SEEDED_REQUESTS: ProcessedRequest[] = [
  // --- MAHADEVAPURA (Dense demand for Water & Roads) ---
  {
    id: 'req-001',
    requestId: 'REQ-2026-08101',
    language: 'kn',
    originalText: 'ನಮ್ಮ ಬಡಾವಣೆಯಲ್ಲಿ ಕಳೆದ ಒಂದು ವಾರದಿಂದ ಕಾವೇರಿ ನೀರು ಪೂರೈಕೆ ಸಂಪೂರ್ಣ ಸ್ಥಗಿತಗೊಂಡಿದೆ. ಟ್ಯಾಂಕರ್ ದಂಧೆ ಹೆಚ್ಚಾಗಿದ್ದು ಸಾಮಾನ್ಯ ಜನರಿಗೆ ಹೊರೆಯಾಗಿದೆ.',
    normalizedText: 'Cauvery water supply has completely stopped in our layout for the past week. Water tanker prices have spiked excessively, causing hardship to residents.',
    translationApplied: true,
    category: 'Water Supply',
    issue: 'Complete disruption in piped water supply and unchecked water tanker exploitation.',
    severity: 'high',
    location: 'Mahadevapura, Hoodi Circle',
    areaId: 'area-mahadevapura',
    areaName: 'Mahadevapura',
    geoResolution: 'area',
    themeId: 'theme-water-shortage',
    processedAt: '2026-09-18T08:30:00Z',
    isTranscript: true
  },
  {
    id: 'req-002',
    requestId: 'REQ-2026-08102',
    language: 'en',
    originalText: 'Severe water pipeline rupture on Outer Ring Road near Doddanekundi. Gallons of drinking water flooding the road while residential complexes have zero supply.',
    normalizedText: 'Severe water pipeline rupture on Outer Ring Road near Doddanekundi. Gallons of drinking water flooding the road while residential complexes have zero supply.',
    translationApplied: false,
    category: 'Water Supply',
    issue: 'Major main line burst leading to severe water wastage and dry residential taps.',
    severity: 'high',
    location: 'Doddanekundi, Mahadevapura',
    areaId: 'area-mahadevapura',
    areaName: 'Mahadevapura',
    geoResolution: 'area',
    themeId: 'theme-pipeline-leak',
    processedAt: '2026-09-18T10:15:00Z',
    isTranscript: false
  },
  {
    id: 'req-003',
    requestId: 'REQ-2026-08103',
    language: 'hi',
    originalText: 'आईटीपीबी रोड पर गहरे गड्ढे हैं, बारिश के बाद जलभराव की वजह से दोपहिया वाहन चालक लगातार गिर रहे हैं। तुरंत मरम्मत की जरूरत है।',
    normalizedText: 'Deep potholes on ITPB road. Waterlogging after rains is causing two-wheeler riders to frequently skid and fall. Immediate repair needed.',
    translationApplied: true,
    category: 'Roads & Transport',
    issue: 'Hazardous potholes and waterlogging causing accidents on high-traffic arterial corridor.',
    severity: 'high',
    location: 'ITPB Main Road, Mahadevapura',
    areaId: 'area-mahadevapura',
    areaName: 'Mahadevapura',
    geoResolution: 'area',
    themeId: 'theme-pothole-hazard',
    processedAt: '2026-09-18T11:45:00Z',
    isTranscript: true
  },
  {
    id: 'req-004',
    requestId: 'REQ-2026-08104',
    language: 'kn',
    originalText: 'ರಾಜಕಾಲುವೆ ಹೂಳು ತೆಗೆಯದ ಕಾರಣ ಸ್ವಲ್ಪ ಮಳೆ ಬಂದರೂ ಮನೆಗಳಿಗೆ ಚರಂಡಿ ನೀರು ನುಗ್ಗುತ್ತಿದೆ. ಡೆಂಗ್ಯೂ ಜ್ವರ ಹರಡುವ ಭೀತಿ ಎದುರಾಗಿದೆ.',
    normalizedText: 'Due to uncleaned stormwater drains (rajakaluve), even slight rain leads to sewage water entering homes. High risk of dengue outbreak.',
    translationApplied: true,
    category: 'Sanitation & Waste',
    issue: 'Un-desilted primary stormwater drain causing domestic flooding and vector-borne disease threat.',
    severity: 'high',
    location: 'Garudacharpalya, Mahadevapura',
    areaId: 'area-mahadevapura',
    areaName: 'Mahadevapura',
    geoResolution: 'area',
    themeId: 'theme-drain-overflow',
    processedAt: '2026-09-18T14:20:00Z',
    isTranscript: false
  },
  {
    id: 'req-005',
    requestId: 'REQ-2026-08105',
    language: 'en',
    originalText: 'Streetlights along the Panathur railway underpass have been dead for three weeks. Pedestrian safety is seriously compromised at night.',
    normalizedText: 'Streetlights along the Panathur railway underpass have been dead for three weeks. Pedestrian safety is seriously compromised at night.',
    translationApplied: false,
    category: 'Electricity & Power',
    issue: 'Prolonged failure of public streetlighting in high-density railway pedestrian underpass.',
    severity: 'medium',
    location: 'Panathur Underpass, Mahadevapura',
    areaId: 'area-mahadevapura',
    areaName: 'Mahadevapura',
    geoResolution: 'area',
    themeId: 'theme-streetlight-failure',
    processedAt: '2026-09-19T09:10:00Z',
    isTranscript: false
  },
  {
    id: 'req-006',
    requestId: 'REQ-2026-08106',
    language: 'kn',
    originalText: 'ಸ್ಥಳೀಯ ಸರ್ಕಾರಿ ಪ್ರಾಥಮಿಕ ಶಾಲೆಯಲ್ಲಿ ಕುಡಿಯುವ ನೀರಿನ ಶುದ್ಧೀಕರಣ ಘಟಕ ಹಾಳಾಗಿದೆ. ಮಕ್ಕಳು ಮನೆಯಿಂದ ಬಾಟಲ್ ತರಬೇಕಾಗಿದೆ.',
    normalizedText: 'Drinking water purifier at local government primary school is broken. Children forced to carry water from home.',
    translationApplied: true,
    category: 'Public Education',
    issue: 'Dysfunctional RO water plant at government school affecting children.',
    severity: 'medium',
    location: 'Hoodi Govt School, Mahadevapura',
    areaId: 'area-mahadevapura',
    areaName: 'Mahadevapura',
    geoResolution: 'area',
    themeId: 'theme-school-infra',
    processedAt: '2026-09-19T11:00:00Z',
    isTranscript: true
  },
  {
    id: 'req-007',
    requestId: 'REQ-2026-08107',
    language: 'en',
    originalText: 'Borewells in our apartment cluster have run completely dry. Request emergency BWSSB tanker supply or deep borewell rejuvenation permission.',
    normalizedText: 'Borewells in our apartment cluster have run completely dry. Request emergency BWSSB tanker supply or deep borewell rejuvenation permission.',
    translationApplied: false,
    category: 'Water Supply',
    issue: 'Groundwater depletion causing acute apartment water shortfall.',
    severity: 'high',
    location: 'Varthur Road, Mahadevapura',
    areaId: 'area-mahadevapura',
    areaName: 'Mahadevapura',
    geoResolution: 'area',
    themeId: 'theme-water-shortage',
    processedAt: '2026-09-19T12:30:00Z',
    isTranscript: false
  },
  {
    id: 'req-008',
    requestId: 'REQ-2026-08108',
    language: 'hi',
    originalText: 'कचरा उठाने वाली गाड़ी पिछले दस दिनों से नहीं आई है। मुख्य चौराहे पर कचरे का बड़ा ढेर लग गया है और बदबू फैल रही है।',
    normalizedText: 'Garbage collection truck has not visited for ten days. Massive open garbage dump created at main junction causing foul stench.',
    translationApplied: true,
    category: 'Sanitation & Waste',
    issue: 'Breakdown of municipal solid waste collection leading to roadside blackspots.',
    severity: 'medium',
    location: 'Kundalahalli Gate, Mahadevapura',
    areaId: 'area-mahadevapura',
    areaName: 'Mahadevapura',
    geoResolution: 'area',
    themeId: 'theme-waste-collection',
    processedAt: '2026-09-19T15:40:00Z',
    isTranscript: false
  },

  // --- BOMMANAHALLI (Stormwater & Drainage, Sewage) ---
  {
    id: 'req-009',
    requestId: 'REQ-2026-08201',
    language: 'kn',
    originalText: 'ಮಳೆ ಬಂದಾಗ ಬೇಗೂರು ರಸ್ತೆಯ ಅಂಡರ್‌ಪಾಸ್ ಸಂಪೂರ್ಣ ಮುಳುಗಡೆಯಾಗುತ್ತದೆ. ಬಸ್ಸುಗಳು ನಿಂತುಹೋಗಿ ಗಂಟೆಗಟ್ಟಲೆ ಟ್ರಾಫಿಕ್ ಜಾಮ್ ಆಗುತ್ತದೆ.',
    normalizedText: 'Begur road underpass gets submerged during rain. Buses get stranded causing hours of heavy vehicular gridlock.',
    translationApplied: true,
    category: 'Roads & Transport',
    issue: 'Chronic underpass submergence during seasonal rains causing transit paralysis.',
    severity: 'high',
    location: 'Begur Main Road, Bommanahalli',
    areaId: 'area-bommanahalli',
    areaName: 'Bommanahalli',
    geoResolution: 'area',
    themeId: 'theme-drain-overflow',
    processedAt: '2026-09-18T09:20:00Z',
    isTranscript: true
  },
  {
    id: 'req-010',
    requestId: 'REQ-2026-08202',
    language: 'en',
    originalText: 'Underground drainage chamber overflowing with sewage onto residential street in Hongasandra. Unbearable stench and risk of waterborne illness.',
    normalizedText: 'Underground drainage chamber overflowing with sewage onto residential street in Hongasandra. Unbearable stench and risk of waterborne illness.',
    translationApplied: false,
    category: 'Sanitation & Waste',
    issue: 'Blocked underground sewer lines causing toxic raw sewage discharge on residential lane.',
    severity: 'high',
    location: 'Hongasandra, Bommanahalli',
    areaId: 'area-bommanahalli',
    areaName: 'Bommanahalli',
    geoResolution: 'area',
    themeId: 'theme-sewage-overflow',
    processedAt: '2026-09-18T11:00:00Z',
    isTranscript: false
  },
  {
    id: 'req-011',
    requestId: 'REQ-2026-08203',
    language: 'hi',
    originalText: 'सरकारी प्राथमिक स्वास्थ्य केंद्र में शाम के समय डॉक्टर उपलब्ध नहीं रहते और जरूरी दवाइयां खत्म हो चुकी हैं।',
    normalizedText: 'No doctors available in the evening at the government primary health center and essential medicines are stocked out.',
    translationApplied: true,
    category: 'Healthcare',
    issue: 'Staff absence and drug stockouts at municipal Primary Health Centre (PHC).',
    severity: 'high',
    location: 'Bommanahalli PHC',
    areaId: 'area-bommanahalli',
    areaName: 'Bommanahalli',
    geoResolution: 'area',
    themeId: 'theme-health-center',
    processedAt: '2026-09-18T16:10:00Z',
    isTranscript: true
  },
  {
    id: 'req-012',
    requestId: 'REQ-2026-08204',
    language: 'en',
    originalText: 'Transformer explosion caused 14 hours of blackout in Bilekahalli. Voltage fluctuations damaged home appliances before power cut.',
    normalizedText: 'Transformer explosion caused 14 hours of blackout in Bilekahalli. Voltage fluctuations damaged home appliances before power cut.',
    translationApplied: false,
    category: 'Electricity & Power',
    issue: 'Distribution transformer burnout causing prolonged outage and voltage surge damage.',
    severity: 'high',
    location: 'Bilekahalli, Bommanahalli',
    areaId: 'area-bommanahalli',
    areaName: 'Bommanahalli',
    geoResolution: 'area',
    themeId: 'theme-power-outage',
    processedAt: '2026-09-19T08:15:00Z',
    isTranscript: false
  },
  {
    id: 'req-013',
    requestId: 'REQ-2026-08205',
    language: 'kn',
    originalText: 'ಕೊಡಿಚಿಕ್ಕನಹಳ್ಳಿ ಮುಖ್ಯ ರಸ್ತೆಯಲ್ಲಿ ರಸ್ತೆ ಅಗೆದು ಪೈಪ್ ಹಾಕಿದ ನಂತರ ಡಾಂಬರೀಕರಣ ಮಾಡಿಲ್ಲ. ಧೂಳು ಹೆಚ್ಚಾಗಿ ಉಸಿರಾಟದ ತೊಂದರೆ ಉಂಟಾಗುತ್ತಿದೆ.',
    normalizedText: 'Kodichikkanahalli main road was dug up for pipes and left unpaved. Extreme dust pollution causing respiratory issues.',
    translationApplied: true,
    category: 'Roads & Transport',
    issue: 'Post-utility trenching left un-asphalted creating severe dust pollution and road hazard.',
    severity: 'medium',
    location: 'Kodichikkanahalli, Bommanahalli',
    areaId: 'area-bommanahalli',
    areaName: 'Bommanahalli',
    geoResolution: 'area',
    themeId: 'theme-unpaved-road',
    processedAt: '2026-09-19T13:45:00Z',
    isTranscript: false
  },

  // --- YELAHANKA (Lake pollution, Piped water, Secondary Roads) ---
  {
    id: 'req-014',
    requestId: 'REQ-2026-08301',
    language: 'kn',
    originalText: 'ಯಲಹಂಕ ಕೆರೆಗೆ ಸಂಸ್ಕರಿಸದ ಕೊಳಚೆ ನೀರು ಹರಿಯುತ್ತಿದ್ದು ಮೀನುಗಳು ಸಾಯುತ್ತಿವೆ. ಸುತ್ತಮುತ್ತಲಿನ ಕೊಳವೆ ಬಾವಿಗಳ ನೀರು ಕಲುಷಿತವಾಗಿದೆ.',
    normalizedText: 'Untreated sewage is entering Yelahanka Lake causing fish mortality. Groundwater and borewells around the perimeter are turning foul.',
    translationApplied: true,
    category: 'Sanitation & Waste',
    issue: 'Industrial and domestic sewage inflow contaminating Yelahanka Lake and shallow aquifers.',
    severity: 'high',
    location: 'Yelahanka Lake Road',
    areaId: 'area-yelahanka',
    areaName: 'Yelahanka',
    geoResolution: 'area',
    themeId: 'theme-lake-pollution',
    processedAt: '2026-09-18T10:05:00Z',
    isTranscript: false
  },
  {
    id: 'req-015',
    requestId: 'REQ-2026-08302',
    language: 'en',
    originalText: 'New extension layouts in Kogilu have no Cauvery water connection yet. Entire community depends on high TDS borewells that damage health.',
    normalizedText: 'New extension layouts in Kogilu have no Cauvery water connection yet. Entire community depends on high TDS borewells that damage health.',
    translationApplied: false,
    category: 'Water Supply',
    issue: 'Absence of piped drinking water network in peripheral residential extension.',
    severity: 'high',
    location: 'Kogilu Layout, Yelahanka',
    areaId: 'area-yelahanka',
    areaName: 'Yelahanka',
    geoResolution: 'area',
    themeId: 'theme-water-shortage',
    processedAt: '2026-09-18T14:50:00Z',
    isTranscript: true
  },
  {
    id: 'req-016',
    requestId: 'REQ-2026-08303',
    language: 'hi',
    originalText: 'एयरपोर्ट रोड से जुड़ने वाली सर्विस रोड की स्ट्रीट लाइटें बंद पड़ी हैं, रात में महिलाओं के लिए चलना सुरक्षित नहीं है।',
    normalizedText: 'Service road connecting to Airport Road has non-functioning streetlights, unsafe for women walking at night.',
    translationApplied: true,
    category: 'Electricity & Power',
    issue: 'Dark service lane creating night safety vulnerability near highway interchange.',
    severity: 'medium',
    location: 'Airport Link Service Road, Yelahanka',
    areaId: 'area-yelahanka',
    areaName: 'Yelahanka',
    geoResolution: 'area',
    themeId: 'theme-streetlight-failure',
    processedAt: '2026-09-19T10:30:00Z',
    isTranscript: false
  },
  {
    id: 'req-017',
    requestId: 'REQ-2026-08304',
    language: 'kn',
    originalText: 'ಅತ್ತೂರು ಬಡಾವಣೆಯಲ್ಲಿ ಸಾರ್ವಜನಿಕ ಉದ್ಯಾನವನದ ಆವರಣ ಗೋಡೆ ಬಿದ್ದಿದ್ದು ರಾತ್ರಿ ಸಮಯದಲ್ಲಿ ಕಿಡಿಗೇಡಿಗಳ ಹಾವಳಿ ಹೆಚ್ಚಾಗಿದೆ.',
    normalizedText: 'Public park boundary wall has collapsed in Attur layout, attracting anti-social elements after dark.',
    translationApplied: true,
    category: 'Roads & Transport',
    issue: 'Dilapidated civic park perimeter compromising community safety.',
    severity: 'low',
    location: 'Attur Layout, Yelahanka',
    areaId: 'area-yelahanka',
    areaName: 'Yelahanka',
    geoResolution: 'area',
    themeId: 'theme-civic-infra',
    processedAt: '2026-09-19T16:20:00Z',
    isTranscript: false
  },

  // --- ANEKAL (Peri-urban healthcare, water, school infrastructure) ---
  {
    id: 'req-018',
    requestId: 'REQ-2026-08401',
    language: 'kn',
    originalText: 'ಅನೇಕಲ್ ತಾಲೂಕು ಆಸ್ಪತ್ರೆಯಲ್ಲಿ ತುರ್ತು ಚಿಕಿತ್ಸಾ ವಿಭಾಗದಲ್ಲಿ ಆಕ್ಸಿಜನ್ ಸೌಲಭ್ಯ ಮತ್ತು ತಜ್ಞ ವೈದ್ಯರ ಕೊರತೆಯಿಂದ ರೋಗಿಗಳನ್ನು ಬೆಂಗಳೂರಿಗೆ ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ.',
    normalizedText: 'Lack of oxygen support and specialist doctors in Anekal Taluk Hospital emergency ward forces critical patients to be referred to Bengaluru city.',
    translationApplied: true,
    category: 'Healthcare',
    issue: 'Critical emergency care deficiency and lack of specialist staff at sub-district hospital.',
    severity: 'high',
    location: 'Anekal Taluk Hospital',
    areaId: 'area-anekal',
    areaName: 'Anekal',
    geoResolution: 'area',
    themeId: 'theme-health-center',
    processedAt: '2026-09-18T08:45:00Z',
    isTranscript: true
  },
  {
    id: 'req-019',
    requestId: 'REQ-2026-08402',
    language: 'en',
    originalText: 'Chandapura-Anekal main road has multiple massive craters due to heavy stone quarry trucks. Daily commuters facing spine injuries and vehicle breakdowns.',
    normalizedText: 'Chandapura-Anekal main road has multiple massive craters due to heavy stone quarry trucks. Daily commuters facing spine injuries and vehicle breakdowns.',
    translationApplied: false,
    category: 'Roads & Transport',
    issue: 'Heavy quarry transport damage causing extensive structural destruction on state highway link.',
    severity: 'high',
    location: 'Chandapura-Anekal Road',
    areaId: 'area-anekal',
    areaName: 'Anekal',
    geoResolution: 'area',
    themeId: 'theme-pothole-hazard',
    processedAt: '2026-09-18T11:20:00Z',
    isTranscript: false
  },
  {
    id: 'req-020',
    requestId: 'REQ-2026-08403',
    language: 'hi',
    originalText: 'गांव में जल जीवन मिशन का पाइप बिछाया गया था लेकिन 6 महीने बाद भी नल में पानी नहीं आया है। हमें 2 किलोमीटर दूर से पानी लाना पड़ता है।',
    normalizedText: 'Pipes were laid under Jal Jeevan Mission in the village but even after 6 months no water flows. We walk 2km to fetch drinking water.',
    translationApplied: true,
    category: 'Water Supply',
    issue: 'Incomplete rural tap connection project with infrastructure installed but non-operational.',
    severity: 'high',
    location: 'Marsur Village, Anekal',
    areaId: 'area-anekal',
    areaName: 'Anekal',
    geoResolution: 'area',
    themeId: 'theme-water-shortage',
    processedAt: '2026-09-19T07:50:00Z',
    isTranscript: true
  },

  // --- BELLANDUR (Lake frothing, Traffic congestion, Waste) ---
  {
    id: 'req-021',
    requestId: 'REQ-2026-08501',
    language: 'en',
    originalText: 'Toxic white foam from Bellandur lake outlet spilling onto Yamalur bridge again. Commuters on two-wheelers are getting foam splashed on their eyes and skin.',
    normalizedText: 'Toxic white foam from Bellandur lake outlet spilling onto Yamalur bridge again. Commuters on two-wheelers are getting foam splashed on their eyes and skin.',
    translationApplied: false,
    category: 'Sanitation & Waste',
    issue: 'Chemical froth spilling from polluted lake weir onto public traffic bridge.',
    severity: 'high',
    location: 'Yamalur Bridge, Bellandur',
    areaId: 'area-bellandur',
    areaName: 'Bellandur',
    geoResolution: 'area',
    themeId: 'theme-lake-pollution',
    processedAt: '2026-09-18T08:10:00Z',
    isTranscript: false
  },
  {
    id: 'req-022',
    requestId: 'REQ-2026-08502',
    language: 'kn',
    originalText: 'ಸರ್ಜಾಪುರ ರಸ್ತೆಯಿಂದ ಬೆಳ್ಳಂದೂರು ಕಡೆಗೆ ಹೋಗುವ ರಸ್ತೆಯಲ್ಲಿ ಒಳಚರಂಡಿ ಕಾಮಗಾರಿಯಿಂದಾಗಿ ಪ್ರತಿದಿನ 2 ಗಂಟೆಗಳ ಕಾಲ ವಾಹನ ದಟ್ಟಣೆ ಉಂಟಾಗುತ್ತಿದೆ.',
    normalizedText: 'Ongoing drainage construction on Sarjapur to Bellandur stretch causes 2-hour gridlock daily. Alternate diversion route urgently required.',
    translationApplied: true,
    category: 'Roads & Transport',
    issue: 'Unmanaged prolonged utility works causing chronic peak hour gridlock.',
    severity: 'medium',
    location: 'Sarjapur-Bellandur Link Road',
    areaId: 'area-bellandur',
    areaName: 'Bellandur',
    geoResolution: 'area',
    themeId: 'theme-pothole-hazard',
    processedAt: '2026-09-18T12:00:00Z',
    isTranscript: true
  },
  {
    id: 'req-023',
    requestId: 'REQ-2026-08503',
    language: 'en',
    originalText: 'Illegal dumping of construction debris along the buffer zone of Bellandur lake at night. Request CCTV installation and strict penalties.',
    normalizedText: 'Illegal dumping of construction debris along the buffer zone of Bellandur lake at night. Request CCTV installation and strict penalties.',
    translationApplied: false,
    category: 'Sanitation & Waste',
    issue: 'Nocturnal debris dumping in lake eco-sensitive buffer zone.',
    severity: 'medium',
    location: 'Bellandur Lake Buffer Zone',
    areaId: 'area-bellandur',
    areaName: 'Bellandur',
    geoResolution: 'area',
    themeId: 'theme-waste-collection',
    processedAt: '2026-09-19T09:40:00Z',
    isTranscript: false
  },

  // --- WHITEFIELD (Tech corridor water, potholes, bus service) ---
  {
    id: 'req-024',
    requestId: 'REQ-2026-08601',
    language: 'en',
    originalText: 'Borewell water in Kadugodi area is highly saline and causing corrosion of pipes and skin dermatitis. Cauvery piped water expansion urgently required.',
    normalizedText: 'Borewell water in Kadugodi area is highly saline and causing corrosion of pipes and skin dermatitis. Cauvery piped water expansion urgently required.',
    translationApplied: false,
    category: 'Water Supply',
    issue: 'Hard saline groundwater causing public health dermatitis and plumbing damage.',
    severity: 'high',
    location: 'Kadugodi, Whitefield',
    areaId: 'area-whitefield',
    areaName: 'Whitefield',
    geoResolution: 'area',
    themeId: 'theme-water-shortage',
    processedAt: '2026-09-18T09:15:00Z',
    isTranscript: false
  },
  {
    id: 'req-025',
    requestId: 'REQ-2026-08602',
    language: 'hi',
    originalText: 'व्हाइटफील्ड रेलवे स्टेशन के पास फुटपाथ पूरी तरह से अतिक्रमण का शिकार है। पैदल चलने वालों को भारी ट्रैफिक के बीच सड़क पर चलना पड़ता है।',
    normalizedText: 'Footpaths near Whitefield railway station are completely encroached. Pedestrians forced to walk on high-speed roadway.',
    translationApplied: true,
    category: 'Roads & Transport',
    issue: 'Encroached walkways forcing pedestrians into moving vehicular streams.',
    severity: 'medium',
    location: 'Whitefield Railway Station Road',
    areaId: 'area-whitefield',
    areaName: 'Whitefield',
    geoResolution: 'area',
    themeId: 'theme-pothole-hazard',
    processedAt: '2026-09-18T15:20:00Z',
    isTranscript: true
  },
  {
    id: 'req-026',
    requestId: 'REQ-2026-08603',
    language: 'kn',
    originalText: 'ಸಾರ್ವಜನಿಕ ಆರೋಗ್ಯ ಕೇಂದ್ರದಲ್ಲಿ ಉಚಿತ ಗರ್ಭಿಣಿ ತಪಾಸಣೆ ಮತ್ತು ಲಸಿಕೆ ಕಾರ್ಯಕ್ರಮ ಸಮರ್ಪಕವಾಗಿ ನಡೆಯುತ್ತಿಲ್ಲ. ಸಿಬ್ಬಂದಿ ಇಲ್ಲ ಎಂದು ಹೇಳುತ್ತಾರೆ.',
    normalizedText: 'Maternal health checkups and childhood immunisation programs are irregular at local primary health clinic due to staff shortages.',
    translationApplied: true,
    category: 'Healthcare',
    issue: 'Disruption in maternal and child health immunization coverage.',
    severity: 'high',
    location: 'Immadihalli PHC, Whitefield',
    areaId: 'area-whitefield',
    areaName: 'Whitefield',
    geoResolution: 'area',
    themeId: 'theme-health-center',
    processedAt: '2026-09-19T10:10:00Z',
    isTranscript: true
  },

  // --- RAJARAJESHWARI NAGAR (Sewage, Road repairs, Electricity) ---
  {
    id: 'req-027',
    requestId: 'REQ-2026-08701',
    language: 'kn',
    originalText: 'ವೃಷಭಾವತಿ ವ್ಯಾಲಿಯಿಂದ ತೀವ್ರವಾದ ದುರ್ವಾಸನೆ ಬರುತ್ತಿದ್ದು, ಸುತ್ತಮುತ್ತಲಿನ ನಿವಾಸಿಗಳಿಗೆ ಉಸಿರಾಟದ ಸಮಸ್ಯೆ ಮತ್ತು ನೊಣಗಳ ಕಾಟ ಹೆಚ್ಚಾಗಿದೆ.',
    normalizedText: 'Heavy industrial chemical stench from Vrishabhavathi canal causing respiratory distress and severe pest infestation in adjoining wards.',
    translationApplied: true,
    category: 'Sanitation & Waste',
    issue: 'Toxic industrial effluent in Vrishabhavathi canal affecting residential air quality.',
    severity: 'high',
    location: 'RR Nagar Vrishabhavathi Valley',
    areaId: 'area-rr-nagar',
    areaName: 'Rajarajeshwari Nagar',
    geoResolution: 'area',
    themeId: 'theme-drain-overflow',
    processedAt: '2026-09-18T10:40:00Z',
    isTranscript: false
  },
  {
    id: 'req-028',
    requestId: 'REQ-2026-08702',
    language: 'en',
    originalText: 'Voltage fluctuations regularly crossing 280V in Ideal Homes Layout. Many air conditioners and fridges damaged this week.',
    normalizedText: 'Voltage fluctuations regularly crossing 280V in Ideal Homes Layout. Many air conditioners and fridges damaged this week.',
    translationApplied: false,
    category: 'Electricity & Power',
    issue: 'Severe grid voltage spikes causing household appliance damage.',
    severity: 'medium',
    location: 'Ideal Homes, RR Nagar',
    areaId: 'area-rr-nagar',
    areaName: 'Rajarajeshwari Nagar',
    geoResolution: 'area',
    themeId: 'theme-power-outage',
    processedAt: '2026-09-19T11:55:00Z',
    isTranscript: false
  },

  // --- KORAMANGALA & HSR LAYOUT ---
  {
    id: 'req-029',
    requestId: 'REQ-2026-08801',
    language: 'en',
    originalText: 'Koramangala 4th block stormwater drain overflowing during thunderstorm, water entered 25 basements including power generators.',
    normalizedText: 'Koramangala 4th block stormwater drain overflowing during thunderstorm, water entered 25 basements including power generators.',
    translationApplied: false,
    category: 'Sanitation & Waste',
    issue: 'Inadequate stormwater discharge capacity causing repeated basement inundation.',
    severity: 'high',
    location: 'Koramangala 4th Block',
    areaId: 'area-koramangala',
    areaName: 'Koramangala',
    geoResolution: 'area',
    themeId: 'theme-drain-overflow',
    processedAt: '2026-09-18T17:30:00Z',
    isTranscript: false
  },
  {
    id: 'req-030',
    requestId: 'REQ-2026-08802',
    language: 'kn',
    originalText: 'ಎಚ್‌ಎಸ್‌ಆರ್ ಲೇಔಟ್ 2ನೇ ಸೆಕ್ಟರ್‌ನಲ್ಲಿ ಮರ ಬಿದ್ದು ವಿದ್ಯುತ್ ತಂತಿ ತುಂಡಾಗಿದೆ. 6 ಗಂಟೆಗಳಿಂದ ವಿದ್ಯುತ್ ಸಂಪರ್ಕ ಕಡಿತಗೊಂಡಿದೆ.',
    normalizedText: 'Tree fall snapped overhead power cable in HSR Layout Sector 2. Power outage persisting for past 6 hours.',
    translationApplied: true,
    category: 'Electricity & Power',
    issue: 'Storm tree fall severed distribution line with delayed BESCOM restoration.',
    severity: 'medium',
    location: 'HSR Layout Sector 2',
    areaId: 'area-hsr-layout',
    areaName: 'HSR Layout',
    geoResolution: 'area',
    themeId: 'theme-power-outage',
    processedAt: '2026-09-19T08:50:00Z',
    isTranscript: true
  },

  // --- PEENYA (Industrial wastewater, road damage, workers healthcare) ---
  {
    id: 'req-031',
    requestId: 'REQ-2026-08901',
    language: 'hi',
    originalText: 'पीन्या 2nd स्टेज में रासायनिक फैक्ट्रियों का दूषित पानी खुले नाले में बहाया जा रहा है, जिससे कामगारों में आंखों में जलन और खांसी की बीमारी हो रही है।',
    normalizedText: 'Chemical factory wastewater is being discharged openly into storm drain in Peenya 2nd Stage, causing eye burns and respiratory illness among industrial workers.',
    translationApplied: true,
    category: 'Healthcare',
    issue: 'Untreated hazardous chemical runoff endangering factory workforce health.',
    severity: 'high',
    location: 'Peenya 2nd Stage',
    areaId: 'area-peenya',
    areaName: 'Peenya Industrial Area',
    geoResolution: 'area',
    themeId: 'theme-health-center',
    processedAt: '2026-09-18T13:10:00Z',
    isTranscript: true
  },
  {
    id: 'req-032',
    requestId: 'REQ-2026-08902',
    language: 'kn',
    originalText: 'ಪೀಣ್ಯ ಮುಖ್ಯ ರಸ್ತೆಯಲ್ಲಿ ರಸ್ತೆ ಗುಂಡಿಗಳಿಂದ ಸರಕು ಸಾಗಣೆ ವಾಹನಗಳು ಪಲ್ಟಿಯಾಗುತ್ತಿವೆ. ತುರ್ತಾಗಿ ಕಾಂಕ್ರೀಟ್ ರಸ್ತೆ ನಿರ್ಮಿಸಬೇಕು.',
    normalizedText: 'Freight and logistics trucks are overturning due to massive craters on Peenya Main Road. Urgent concrete paving needed.',
    translationApplied: true,
    category: 'Roads & Transport',
    issue: 'Industrial freight road structural collapse creating transport hazard.',
    severity: 'high',
    location: 'Peenya Industrial Main Road',
    areaId: 'area-peenya',
    areaName: 'Peenya Industrial Area',
    geoResolution: 'area',
    themeId: 'theme-pothole-hazard',
    processedAt: '2026-09-19T14:15:00Z',
    isTranscript: false
  },

  // --- KR PURAM & MARATHAHALLI ---
  {
    id: 'req-033',
    requestId: 'REQ-2026-09001',
    language: 'kn',
    originalText: 'ಕೆಆರ್ ಪುರಂ ಸೇತುವೆ ಕೆಳಗೆ ಕಸದ ರಾಶಿಗೆ ಬೆಂಕಿ ಹಚ್ಚಲಾಗಿದ್ದು, ವಿಷಕಾರಿ ಹೊಗೆಯಿಂದ ಸುತ್ತಮುತ್ತಲಿನ ಶಾಲೆ ಮಕ್ಕಳಿಗೆ ಉಸಿರುಗಟ್ಟುತ್ತಿದೆ.',
    normalizedText: 'Open garbage burning beneath KR Puram suspension bridge creating toxic acrid smoke affecting nearby school children.',
    translationApplied: true,
    category: 'Sanitation & Waste',
    issue: 'Illegal municipal solid waste incineration under transit overpass.',
    severity: 'high',
    location: 'KR Puram Bridge',
    areaId: 'area-kr-puram',
    areaName: 'KR Puram (K.R. Pura)',
    geoResolution: 'area',
    themeId: 'theme-waste-collection',
    processedAt: '2026-09-18T11:30:00Z',
    isTranscript: false
  },
  {
    id: 'req-034',
    requestId: 'REQ-2026-09002',
    language: 'en',
    originalText: 'Water pipelines laid 2 years ago in TC Palya remain dry as feeder connection to master balancing reservoir has not been executed.',
    normalizedText: 'Water pipelines laid 2 years ago in TC Palya remain dry as feeder connection to master balancing reservoir has not been executed.',
    translationApplied: false,
    category: 'Water Supply',
    issue: 'Completed distribution network idling without trunk feeder line linkage.',
    severity: 'high',
    location: 'TC Palya, KR Puram',
    areaId: 'area-kr-puram',
    areaName: 'KR Puram (K.R. Pura)',
    geoResolution: 'area',
    themeId: 'theme-water-shortage',
    processedAt: '2026-09-19T10:45:00Z',
    isTranscript: false
  },

  // --- ELECTRONIC CITY & SARJAPUR ---
  {
    id: 'req-035',
    requestId: 'REQ-2026-09101',
    language: 'en',
    originalText: 'Piped water infrastructure missing in Doddathoguru village adjoining Electronic City Phase 1. Villagers dependent on unregulated water mafia.',
    normalizedText: 'Piped water infrastructure missing in Doddathoguru village adjoining Electronic City Phase 1. Villagers dependent on unregulated water mafia.',
    translationApplied: false,
    category: 'Water Supply',
    issue: 'Severe contrast between tech park infrastructure and adjacent un-served village settlement.',
    severity: 'high',
    location: 'Doddathoguru, Electronic City',
    areaId: 'area-electronic-city',
    areaName: 'Electronic City',
    geoResolution: 'area',
    themeId: 'theme-water-shortage',
    processedAt: '2026-09-18T09:40:00Z',
    isTranscript: false
  },
  {
    id: 'req-036',
    requestId: 'REQ-2026-09102',
    language: 'hi',
    originalText: 'सरजापुर रोड पर ड्रेन का ढक्कन टूटा हुआ है, कल रात एक साइकिल सवार उसमें गिरकर घायल हो गया।',
    normalizedText: 'Broken stormwater drain slab on Sarjapur road. A cyclist fell inside and got injured last night.',
    translationApplied: true,
    category: 'Roads & Transport',
    issue: 'Missing storm drain cover slab posing fatal risk on pedestrian sidewalk.',
    severity: 'high',
    location: 'Sarjapur Road near Carmelaram',
    areaId: 'area-sarjapur',
    areaName: 'Sarjapur Road Corridor',
    geoResolution: 'area',
    themeId: 'theme-pothole-hazard',
    processedAt: '2026-09-19T07:30:00Z',
    isTranscript: true
  },

  // --- DASARAHALLI & KENGERI ---
  {
    id: 'req-037',
    requestId: 'REQ-2026-09201',
    language: 'kn',
    originalText: 'ದಾಸರಹಳ್ಳಿ ವಲಯದ ಚೊಕ್ಕಸಂದ್ರದಲ್ಲಿ ರಸ್ತೆ ದೀಪಗಳು ಇಲ್ಲದೆ ಅಪರಾಧ ಪ್ರಕರಣಗಳು ಹೆಚ್ಚಾಗುತ್ತಿವೆ. ಪೊಲೀಸ್ ಗಸ್ತು ಹೆಚ್ಚಿಸಬೇಕು.',
    normalizedText: 'Lack of street illumination in Chokkasandra, Dasarahalli zone leading to rising street crimes and snatchings. Urgent lighting needed.',
    translationApplied: true,
    category: 'Electricity & Power',
    issue: 'Dark arterial street sectors compromising personal safety.',
    severity: 'medium',
    location: 'Chokkasandra, Dasarahalli',
    areaId: 'area-dasarahalli',
    areaName: 'Dasarahalli',
    geoResolution: 'area',
    themeId: 'theme-streetlight-failure',
    processedAt: '2026-09-18T16:40:00Z',
    isTranscript: false
  },
  {
    id: 'req-038',
    requestId: 'REQ-2026-09202',
    language: 'kn',
    originalText: 'ಕೆಂಗೇರಿ ಉಪನಗರದಲ್ಲಿ ಸರ್ಕಾರಿ ಶಾಲೆಯ ಶೌಚಾಲಯಗಳಿಗೆ ನೀರಿನ ಸಂಪರ್ಕವಿಲ್ಲದೆ ವಿದ್ಯಾರ್ಥಿನಿಯರು ಶಾಲೆ ಬಿಡುವ ಪರಿಸ್ಥಿತಿ ಬಂದಿದೆ.',
    normalizedText: 'Government school toilets in Kengeri Satellite Town lack running water connection, severely affecting girl students retention.',
    translationApplied: true,
    category: 'Public Education',
    issue: 'Lack of running water sanitation in public school affecting adolescent girls education.',
    severity: 'high',
    location: 'Kengeri Satellite Town',
    areaId: 'area-kengeri',
    areaName: 'Kengeri',
    geoResolution: 'area',
    themeId: 'theme-school-infra',
    processedAt: '2026-09-19T09:05:00Z',
    isTranscript: true
  }
];

// Helper to expand seed requests into 120+ structured items programmatically
export function getFullSeededDataset(): ProcessedRequest[] {
  const fullList: ProcessedRequest[] = [...SEEDED_REQUESTS];
  
  // Clone and diversify requests to reach 125 realistic items across all 28 areas
  const templatePool = SEEDED_REQUESTS;
  const areaIds = [
    'area-mahadevapura', 'area-bommanahalli', 'area-yelahanka', 'area-anekal',
    'area-whitefield', 'area-bellandur', 'area-electronic-city', 'area-rr-nagar',
    'area-dasarahalli', 'area-kengeri', 'area-peenya', 'area-hebbal',
    'area-koramangala', 'area-hsr-layout', 'area-marathahalli', 'area-kr-puram',
    'area-jayanagar', 'area-btm-layout', 'area-banashankari', 'area-vijayanagar',
    'area-rajajinagar', 'area-malleshwaram', 'area-yeshwanthpur', 'area-shivajinagar',
    'area-indiranagar', 'area-sarjapur', 'area-bangalore-north', 'area-bangalore-south'
  ];

  let idCounter = 39;
  
  // Weight demand distribution so Mahadevapura, Bommanahalli, Yelahanka, Anekal, Whitefield emerge as top hotspots
  const areaWeights: Record<string, number> = {
    'area-mahadevapura': 16,
    'area-bommanahalli': 14,
    'area-yelahanka': 11,
    'area-anekal': 10,
    'area-whitefield': 9,
    'area-bellandur': 8,
    'area-kr-puram': 7,
    'area-peenya': 6,
    'area-electronic-city': 6,
    'area-rr-nagar': 5,
    'area-sarjapur': 5,
    'area-koramangala': 4,
    'area-hsr-layout': 4,
    'area-dasarahalli': 4,
    'area-kengeri': 3,
    'area-hebbal': 3,
    'area-marathahalli': 3,
    'area-banashankari': 2,
    'area-bangalore-north': 2,
    'area-bangalore-south': 2,
    'area-jayanagar': 2,
    'area-btm-layout': 2,
    'area-vijayanagar': 1,
    'area-rajajinagar': 1,
    'area-malleshwaram': 1,
    'area-yeshwanthpur': 1,
    'area-shivajinagar': 1,
    'area-indiranagar': 1
  };

  for (const areaId of areaIds) {
    const targetCount = areaWeights[areaId] || 2;
    const currentCount = fullList.filter(r => r.areaId === areaId).length;
    const needed = targetCount - currentCount;

    for (let i = 0; i < needed; i++) {
      const template = templatePool[(idCounter + i) % templatePool.length];
      const hoursAgo = ((idCounter * 3) % 72) + 1;
      const date = new Date(Date.now() - hoursAgo * 3600 * 1000).toISOString();

      fullList.push({
        ...template,
        id: `req-${String(idCounter).padStart(3, '0')}`,
        requestId: `REQ-2026-${String(80000 + idCounter)}`,
        areaId,
        areaName: areaId.replace('area-', '').split('-').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join(' '),
        location: `${template.location.split(',')[0]}, ${areaId.replace('area-', '')}`,
        processedAt: date,
        isTranscript: (idCounter % 3 === 0)
      });
      idCounter++;
    }
  }

  return fullList;
}
